-- AlterTable
ALTER TABLE "public"."Stats" ALTER COLUMN "currStrXp" DROP NOT NULL,
ALTER COLUMN "currDexXp" DROP NOT NULL,
ALTER COLUMN "currIntXp" DROP NOT NULL,
ALTER COLUMN "currCharXp" DROP NOT NULL;
